# Generated by Django 5.0.3 on 2026-02-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_society_alter_user_role_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('ADMIN', 'Admin'), ('OWNER', 'Owner')], max_length=10),
        ),
        migrations.CreateModel(
            name='MaintanenceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=10)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flat')),
            ],
        ),
    ]
