# Generated by Django 5.0.3 on 2026-02-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role_maintanencebill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('TENANT', 'Tenant')], max_length=10),
        ),
    ]
