# Generated by Django 6.0.2 on 2026-02-10 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_maintanencebill_maintenencebill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenencebill',
            name='status',
        ),
        migrations.AddField(
            model_name='maintenencebill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenencebill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maintenencebill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenencebill',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
