# Generated by Django 5.0.3 on 2026-02-11 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_flat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_flats', to=settings.AUTH_USER_MODEL),
        ),
    ]
